name: Performance Testing K6
on:
    push:
      branches:
        - master
jobs:
    k6_cloud_test:
        name: k6 cloud test run
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
      
          - name: Run k6 cloud test
            uses: k6io/action@v0.1
            with:
              filename: ./scenarios/tc02_CRUD_operations.js
              cloud: true
              token: ${{ secrets.K6_CLOUD_API_TOKEN }}